# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MMatrixToNumericMatrix <- function(pM, datatype) {
    .Call('_MarsuMatrix_MMatrixToNumericMatrix', PACKAGE = 'MarsuMatrix', pM, datatype)
}

restore_mmatrix_ <- function(datatype, file, nrow, ncol) {
    .Call('_MarsuMatrix_restore_mmatrix_', PACKAGE = 'MarsuMatrix', datatype, file, nrow, ncol)
}

